# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: BedDeM CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Prepare
      run: |
        curl -s https://drive.switch.ch/index.php/s/JmxKrMLdqGeriGV/download --output plugins.zip
        unzip -q plugins.zip
    - name: Build with Ant
      run: ant build "-DECLIPSE_HOME=$(pwd)"
    - name: Run tests
      run: |
        ant run-test "-DECLIPSE_HOME=$(pwd)"
        ant junitreport
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: |
          junit/**/*.xml

